openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: wabli-contest-82206
  url: http://83.212.100.226:3008/v1
security:
- {}
tags:
- description: not yet ready
  name: trip
paths:
  /trip:
    post:
      operationId: createtrip
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/trip'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trip'
          description: successful operation
      summary: Creates the data
      tags:
      - trip
      x-eov-operation-handler: controllers/TripController
  /trip/{tripId}:
    delete:
      operationId: deletetrip
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: tripId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - trip
      x-eov-operation-handler: controllers/TripController
    get:
      operationId: gettrip
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: tripId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trip'
          description: successful operation
      summary: Get the element
      tags:
      - trip
      x-eov-operation-handler: controllers/TripController
    put:
      operationId: updatetrip
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: tripId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/trip'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trip'
          description: successful operation
      summary: Updates the element
      tags:
      - trip
      x-eov-operation-handler: controllers/TripController
  /trip/getAll:
    get:
      operationId: getAlltrip
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/trip'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - trip
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/TripController
components:
  schemas:
    trip:
      example:
        _id: _id
        TripTitle: TripTitle
      properties:
        _id:
          type: string
        TripTitle:
          type: string
      required:
      - TripTitle
      type: object
